author:
  name: Trevor Smale
  email: smaletrevor@gmail.com
  title: Introduction to Blender
  description: This course is designed to give uninitiated participants basic working proficiency with the software and a basic general understanding of 3D graphics principles.

# Build settings
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

